name: Push Docker Image aw-monitoring-ether to ECR

on:
  push:
    branches:
      - main
      - master
      - dev
      - ether
    paths:
      - './**'
      - '.github/workflows/ether-monitoring.yaml'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build, tag, and push image aw-monitoring-ether to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_MONITORING_ETHER }}
        IMAGE_TAG: latest
      run: |
        docker build -f ./api-twitter/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        echo "Pushing image to ECR aw-monitoring-ether ..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >>$GITHUB_OUTPUT
    - name: Log out of Amazon ECR
      if: always ()
      run: docker logout ${{ steps.login-ecr.outputs.registry }}
